/* Smart Med production-style client application.
   Uses browser storage for a zero-backend deployment and NLM RxNorm for medicine normalization.
   For real clinical deployment, add authenticated backend, encrypted database, audit logs,
   validated interaction content/licensing, consent management and regulated-device review.
*/
(() => {
  const STORE='smartmed-prod-v1';
  const seed={profile:{name:'',dob:'',phone:'',email:'',blood:'',emergencyName:'',emergencyPhone:''},meds:[],doses:[],allergies:[],conditions:[],careTeam:[],settings:{reminders:true,caregiverAlerts:false},activity:[]};
  let state=JSON.parse(localStorage.getItem(STORE)||'null')||seed;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
  const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random();
  const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)};
  const today=()=>new Date().toISOString().slice(0,10);
  const activeMeds=()=>state.meds.filter(m=>m.active);
  function log(x){state.activity.unshift({id:id(),at:new Date().toISOString(),text:x});state.activity=state.activity.slice(0,100);save()}
  async function rxLookup(q){if(!q)return[];try{const u='https://rxnav.nlm.nih.gov/REST/drugs.json?name='+encodeURIComponent(q);const r=await fetch(u);if(!r.ok)return[];const j=await r.json();const g=j?.drugGroup?.conceptGroup||[];return g.flatMap(x=>x.conceptProperties||[]).slice(0,8)}catch(e){return[]}}
  function checkLocalInteractions(names){const fn=window.SmartMedSafety?.check;if(fn)return fn(names.map(name=>({name})),{diseases:state.conditions,allergies:state.allergies});return[]}
  function nav(){return `<aside class="sidebar"><button class="nav active" data-page="home">⌂ Overview</button><button class="nav" data-page="meds">▣ Medicines</button><button class="nav" data-page="schedule">◷ Schedule</button><button class="nav" data-page="safety">⚕ Safety</button><button class="nav" data-page="adherence">✓ Adherence</button><button class="nav" data-page="refills">↻ Refills</button><button class="nav" data-page="records">▤ Health record</button><button class="nav" data-page="care">♙ Care team</button><button class="nav" data-page="settings">⚙ Settings</button></aside>`}
  function shell(page){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));}
  function home(){const meds=activeMeds();const due=meds.reduce((n,m)=>n+m.times.length,0);const week=state.doses.filter(d=>Date.now()-new Date(d.at).getTime()<604800000);const pct=week.length?Math.round(week.filter(d=>d.status==='taken').length/week.length*100):0;const alerts=checkLocalInteractions(meds.map(m=>m.name));return `<section class="hero"><div><span class="eyebrow">SMART MED</span><h1>${state.profile.name?`Hello, ${esc(state.profile.name)}`:'Your medication safety center'}</h1><p>One secure place for medicines, reminders, adherence, refills and medication-safety review.</p></div><button class="btn white" data-page="meds">+ Add medicine</button></section><div class="stats"><div class="stat"><span>Active medicines</span><b>${meds.length}</b></div><div class="stat"><span>Doses scheduled today</span><b>${due}</b></div><div class="stat"><span>7-day recorded adherence</span><b>${pct}%</b></div><div class="stat"><span>Safety alerts</span><b>${alerts.length}</b></div></div><div class="columns"><div class="card"><div class="cardhead"><h2>Today's plan</h2><button class="link" data-page="schedule">View all</button></div>${doseList()}</div><div class="card"><div class="cardhead"><h2>Safety status</h2><button class="link" data-page="safety">Review</button></div><div class="safetybig ${alerts.length?'warning':'safe'}">${alerts.length?'⚠':'✓'} ${alerts.length?alerts.length+' alert(s) need review':'No alerts in the current screening rules'}</div><p class="muted small">Always confirm important decisions with your pharmacist/doctor. No screening database is complete.</p></div></div>`}
  function doseList(){const rows=activeMeds().flatMap(m=>m.times.map(t=>({m,t}))).sort((a,b)=>a.t.localeCompare(b.t));if(!rows.length)return '<div class="empty">No medicines scheduled. Add a medicine to create your schedule.</div>';return rows.map(x=>{const done=state.doses.find(d=>d.date===today()&&d.medId===x.m.id&&d.time===x.t);return `<div class="dose"><div class="time">${esc(x.t)}</div><div class="dosemain"><b>${esc(x.m.name)}</b><span>${esc(x.m.dose)} · ${esc(x.m.route||'Oral')}</span></div><div>${done?.status==='taken'?'<span class="tag good">Taken</span>':done?.status==='skipped'?'<span class="tag">Skipped</span>':`<button class="mini primary" data-dose="${x.m.id}|${x.t}|taken">Take</button> <button class="mini" data-dose="${x.m.id}|${x.t}|skipped">Skip</button>`}</div></div>`}).join('')}
  function meds(){return `<div class="pagehead"><div><h1>Medicines</h1><p>Manage prescriptions, schedules, stock and verification status.</p></div><button class="btn primary" id="newMed">+ Add medicine</button></div><div class="card">${state.meds.length?state.meds.map(m=>`<div class="medrow"><div class="avatar">${esc(m.name[0]||'M')}</div><div class="medinfo"><h3>${esc(m.name)}</h3><p>${esc(m.dose)} · ${esc(m.route||'Oral')} · ${m.times.length?m.times.join(', '):'No times set'}</p><div><span class="tag ${m.active?'good':'mutedtag'}">${m.active?'Active':'Stopped'}</span> <span class="tag">${m.verification||'Self-entered'}</span>${m.stock!=null?` <span class="tag">${m.stock} doses left</span>`:''}</div></div><div class="actions"><button class="mini" data-edit="${m.id}">Edit</button>${m.active?`<button class="mini" data-stop="${m.id}">Stop</button>`:''}</div></div>`).join(''):'<div class="empty">Your medication list is empty.</div>')}</div>`}
  function schedule(){return `<div class="pagehead"><div><h1>Dose schedule</h1><p>Record every dose. Reminders require browser notification permission.</p></div><button class="btn primary" id="enableNotify">Enable reminders</button></div><div class="card">${doseList()}</div><div class="card"><h2>Recent dose history</h2>${state.doses.slice(0,30).map(d=>`<div class="history"><b>${esc(d.date)} ${esc(d.time)}</b><span>${esc(d.medName)}</span><span class="tag ${d.status==='taken'?'good':''}">${esc(d.status)}</span></div>`).join('')||'<div class="empty">No dose history yet.</div>'}</div>`}
  function safety(){const alerts=checkLocalInteractions(activeMeds().map(m=>m.name));return `<div class="pagehead"><div><h1>Medication safety</h1><p>Screen current medicines, conditions and documented allergies.</p></div><button class="btn primary" id="runSafety">Run safety check</button></div><div class="card"><h2>Current medicines</h2>${activeMeds().map(m=>`<div class="history"><span>${esc(m.name)}</span><span>${esc(m.dose)}</span></div>`).join('')||'<div class="empty">No active medicines.</div>'}</div><div class="card"><h2>Screening results</h2>${alerts.length?alerts.map(a=>`<div class="alert ${a.sev==='Major'||a.sev==='Contraindicated'?'bad':'warn'}"><b>${esc(a.sev)} · ${esc(a.type)}</b><div>${esc((a.medicines||[]).join(' + '))}</div><p>${esc(a.effect)}</p><small>${esc(a.action||'Professional review recommended.')}</small></div>`).join(''):'<div class="safeBox">✓ No alert found in the current embedded ruleset.</div>'}<p class="muted small">This is decision support, not a diagnosis or a complete interaction database. Drug labels and authoritative clinical references should be checked for prescribing decisions.</p></div>`}
  function adherence(){const last=state.doses.filter(d=>Date.now()-new Date(d.at).getTime()<604800000);const p=last.length?Math.round(last.filter(d=>d.status==='taken').length/last.length*100):0;return `<div class="pagehead"><div><h1>Adherence</h1><p>Track missed doses and improve medication-taking consistency.</p></div></div><div class="card"><div class="adhero"><span>Recorded 7-day adherence</span><b>${p}%</b><div class="bar"><i style="width:${p}%"></i></div></div>${activeMeds().map(m=>`<div class="history"><span><b>${esc(m.name)}</b></span><span>${m.adherence?.filter(Boolean).length||0}/${m.adherence?.length||0} recorded</span></div>`).join('')}</div>`}
  function refills(){return `<div class="pagehead"><div><h1>Refills</h1><p>Monitor remaining doses and refill dates.</p></div></div><div class="card">${activeMeds().map(m=>{const left=m.stock??0;const days=m.times.length?Math.floor(left/m.times.length):0;return `<div class="refill"><div><b>${esc(m.name)}</b><p class="muted small">${left} doses estimated · about ${days} day(s) at current schedule</p></div><span class="tag ${days<=7?'warn':'good'}">${days<=7?'Refill soon':'OK'}</span></div>`}).join('')||'<div class="empty">No active medicines.</div>'}</div>`}
  function records(){return `<div class="pagehead"><div><h1>Health record</h1><p>Conditions and allergies used for safety screening.</p></div><button class="btn primary" id="editRecord">Edit profile</button></div><div class="columns"><div class="card"><h2>Patient</h2><p><b>${esc(state.profile.name||'Not set')}</b></p><p>${esc(state.profile.phone||'No phone')}</p><p>Blood group: ${esc(state.profile.blood||'Not set')}</p></div><div class="card"><h2>Allergies</h2><p>${state.allergies.map(esc).join(', ')||'None recorded'}</p><h2>Conditions</h2><p>${state.conditions.map(esc).join(', ')||'None recorded'}</p></div></div>`}
  function care(){return `<div class="pagehead"><div><h1>Care team</h1><p>People involved in medication support.</p></div><button class="btn primary" id="addCare">+ Add contact</button></div><div class="card">${state.careTeam.map(c=>`<div class="history"><span><b>${esc(c.name)}</b><br><small>${esc(c.role)}</small></span><span>${esc(c.phone)}</span></div>`).join('')||'<div class="empty">No care-team contacts added.</div>'}</div>`}
  function settings(){return `<div class="pagehead"><div><h1>Settings & privacy</h1><p>Control reminders and local data.</p></div></div><div class="card"><label class="toggle"><input id="reminders" type="checkbox" ${state.settings.reminders?'checked':''}> Medication reminders</label><label class="toggle"><input id="careAlerts" type="checkbox" ${state.settings.caregiverAlerts?'checked':''}> Caregiver alerts</label><hr><button class="btn dangerbtn" id="clearData">Delete local Smart Med data</button></div><div class="card"><h2>About clinical data</h2><p class="small muted">RxNorm is used for medication-name normalization. Official labels should be consulted for prescribing information. This browser-only build stores data locally on the device.</p></div>`}
  function modal(title,body){const x=document.createElement('div');x.className='modal';x.innerHTML=`<div class="sheet"><div class="sheethead"><h2>${title}</h2><button class="close">×</button></div>${body}</div>`;document.body.appendChild(x);x.querySelector('.close').onclick=()=>x.remove();return x}
  function medForm(existing){const m=existing||{name:'',dose:'',route:'Oral',times:['08:00'],stock:30,active:true,verification:'Self-entered'};return `<form id="medForm"><label>Medicine name<input id="mn" value="${esc(m.name)}" required autocomplete="off"><div id="suggest" class="suggest"></div></label><div class="two"><label>Strength / dose<input id="md" value="${esc(m.dose)}" placeholder="e.g. 500 mg" required></label><label>Route<select id="mr"><option ${m.route==='Oral'?'selected':''}>Oral</option><option ${m.route==='Topical'?'selected':''}>Topical</option><option ${m.route==='Inhaled'?'selected':''}>Inhaled</option><option ${m.route==='Injection'?'selected':''}>Injection</option><option ${m.route==='Other'?'selected':''}>Other</option></select></label></div><label>Times (24-hour, comma separated)<input id="mt" value="${esc(m.times.join(', '))}" placeholder="08:00, 20:00"></label><label>Approximate doses in stock<input id="ms" type="number" min="0" value="${m.stock??30}"></label><button class="btn primary" type="submit">Save medicine</button></form>`}
  function profileForm(){return `<form id="profileForm"><label>Full name<input id="pn" value="${esc(state.profile.name)}" required></label><div class="two"><label>Date of birth<input id="pd" type="date" value="${esc(state.profile.dob)}"></label><label>Blood group<input id="pb" value="${esc(state.profile.blood)}"></label></div><label>Phone<input id="pp" value="${esc(state.profile.phone)}"></label><label>Allergies<input id="pa" value="${esc(state.allergies.join(', '))}" placeholder="penicillin, aspirin"></label><label>Medical conditions<input id="pc" value="${esc(state.conditions.join(', '))}" placeholder="diabetes, hypertension"></label><label>Emergency contact name<input id="pe" value="${esc(state.profile.emergencyName)}"></label><label>Emergency contact phone<input id="pep" value="${esc(state.profile.emergencyPhone)}"></label><button class="btn primary">Save record</button></form>`}
  function render(page='home'){page=page||'home';shell(page);const content=({home,meds,schedule,safety,adherence,refills,records,care,settings}[page]||home)();$('#app').innerHTML=nav()+`<main>${content}</main>`;bind()}
  function bind(){
    $$('[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));
    $('#newMed')?.addEventListener('click',()=>openMed());$('#addCare')?.addEventListener('click',()=>openCare());$('#editRecord')?.addEventListener('click',()=>openProfile());$('#enableNotify')?.addEventListener('click',enableNotify);$('#runSafety')?.addEventListener('click',()=>render('safety'));
    $$('[data-dose]').forEach(b=>b.onclick=()=>takeDose(b.dataset.dose));$$('[data-stop]').forEach(b=>b.onclick=()=>{const m=state.meds.find(x=>x.id===b.dataset.stop);if(m){m.active=false;log(`Stopped ${m.name}`);render('meds')}});$$('[data-edit]').forEach(b=>{const m=state.meds.find(x=>x.id===b.dataset.edit);openMed(m)});
    $('#reminders')?.addEventListener('change',e=>{state.settings.reminders=e.target.checked;save()});$('#careAlerts')?.addEventListener('change',e=>{state.settings.caregiverAlerts=e.target.checked;save()});$('#clearData')?.addEventListener('click',()=>{if(confirm('Delete all locally stored Smart Med data?')){localStorage.removeItem(STORE);location.reload()}});
  }
  function openMed(existing){const x=modal(existing?'Edit medicine':'Add medicine',medForm(existing));const input=x.querySelector('#mn'),suggest=x.querySelector('#suggest');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const r=await rxLookup(input.value);suggest.innerHTML=r.map(v=>`<button type="button" data-name="${esc(v.name||v.synonym||'')}">${esc(v.name||v.synonym||'')}</button>`).join('');suggest.querySelectorAll('button').forEach(b=>b.onclick=()=>{input.value=b.dataset.name;suggest.innerHTML=''})},350)};x.querySelector('#medForm').onsubmit=e=>{e.preventDefault();const name=input.value.trim();const times=x.querySelector('#mt').value.split(',').map(s=>s.trim()).filter(Boolean);if(!name||!times.length)return;const conflict=checkLocalInteractions([name,...activeMeds().filter(m=>!existing||m.id!==existing.id).map(m=>m.name)]);if(conflict.length&& !confirm(`Safety screening found ${conflict.length} alert(s). Save for professional review?`))return;const m=existing||{id:id(),active:true};Object.assign(m,{name,dose:x.querySelector('#md').value.trim(),route:x.querySelector('#mr').value,times,stock:Number(x.querySelector('#ms').value||0),verification:'Self-entered'});if(!existing)state.meds.push(m);save();log(`${existing?'Updated':'Added'} ${name}`);x.remove();toast('Medicine saved');render('meds')}}
  function openProfile(){const x=modal('Patient health record',profileForm());x.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();state.profile.name=x.querySelector('#pn').value;state.profile.dob=x.querySelector('#pd').value;state.profile.blood=x.querySelector('#pb').value;state.profile.phone=x.querySelector('#pp').value;state.allergies=x.querySelector('#pa').value.split(',').map(s=>s.trim()).filter(Boolean);state.conditions=x.querySelector('#pc').value.split(',').map(s=>s.trim()).filter(Boolean);state.profile.emergencyName=x.querySelector('#pe').value;state.profile.emergencyPhone=x.querySelector('#pep').value;save();log('Updated health record');x.remove();render('records')}}
  function openCare(){const x=modal('Add care-team contact',`<form id="careForm"><label>Name<input id="cn" required></label><label>Role<input id="cr" placeholder="Caregiver / doctor / pharmacist" required></label><label>Phone<input id="cp"></label><button class="btn primary">Save contact</button></form>`);x.querySelector('#careForm').onsubmit=e=>{e.preventDefault();state.careTeam.push({id:id(),name:x.querySelector('#cn').value,role:x.querySelector('#cr').value,phone:x.querySelector('#cp').value});save();x.remove();render('care')}}
  function takeDose(spec){const [medId,time,status]=spec.split('|'),m=state.meds.find(x=>x.id===medId);if(!m)return;state.doses.unshift({id:id(),medId,date:today(),time,status,medName:m.name,at:new Date().toISOString()});m.adherence=m.adherence||[];m.adherence.push(status==='taken'?1:0);m.adherence=m.adherence.slice(-30);if(status==='taken'&&m.stock>0)m.stock--;save();log(`${m.name}: ${status}`);toast(status==='taken'?'Dose recorded':'Dose skipped');render('schedule')}
  async function enableNotify(){if(!('Notification'in window)){toast('Notifications are not supported by this browser');return}const p=await Notification.requestPermission();toast(p==='granted'?'Medication notifications enabled':'Notification permission not granted')}
  function notificationLoop(){if(!state.settings.reminders||Notification.permission!=='granted')return;const now=new Date(),hh=String(now.getHours()).padStart(2,'0'),mm=String(now.getMinutes()).padStart(2,'0');activeMeds().forEach(m=>m.times.forEach(t=>{if(t===hh+':'+mm&&!state.doses.some(d=>d.date===today()&&d.medId===m.id&&d.time===t)){new Notification('Smart Med reminder',{body:`Time for ${m.name} ${m.dose}`})}}))}
  document.addEventListener('click',e=>{if(e.target.matches('.link,[data-page]')){const p=e.target.dataset.page;if(p)render(p)}});
  $('#app')?.insertAdjacentHTML('afterbegin','');
  document.addEventListener('DOMContentLoaded',()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render('home');setInterval(notificationLoop,30000)});
})();