/* Smart Med Competition Layer v4: assistive prescription scanner + structured extraction + pharmacist verification + schedule builder. */
(()=>{
'use strict';
const KEY='smartmed:v3';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}};
const set=x=>localStorage.setItem(KEY,JSON.stringify(x));
const toast=m=>{const t=document.getElementById('toast');if(t){t.hidden=false;t.className='toast';t.textContent=m;setTimeout(()=>t.hidden=true,2600)}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const DRUGS=['Paracetamol','Ibuprofen','Aceclofenac','Diclofenac','Naproxen','Mefenamic Acid','Amoxicillin','Amoxicillin + Clavulanate','Azithromycin','Cefixime','Cefuroxime','Doxycycline','Pantoprazole','Omeprazole','Rabeprazole','Ondansetron','Cetirizine','Levocetirizine','Amlodipine','Telmisartan','Losartan','Olmesartan','Ramipril','Metoprolol','Atorvastatin','Rosuvastatin','Clopidogrel','Aspirin','Warfarin','Apixaban','Rivaroxaban','Metformin','Glimepiride','Gliclazide','Sitagliptin','Empagliflozin','Dapagliflozin','Levothyroxine','Prednisolone','Dexamethasone','Methotrexate','Allopurinol','Tamsulosin','Finasteride','Clonazepam','Alprazolam','Escitalopram','Sertraline','Fluoxetine','Pregabalin','Gabapentin','Duloxetine','Levetiracetam','Sodium Valproate','Carbamazepine','Tramadol'];
const RULES=[[/warfarin/i,/ibuprofen|diclofenac|naproxen|mefenamic|aceclofenac/i,'high','Bleeding risk'],[/warfarin/i,/aspirin|clopidogrel/i,'high','Major bleeding risk'],[/warfarin/i,/clarithromycin|erythromycin|azithromycin/i,'moderate','May increase INR/bleeding risk'],[/rivaroxaban|apixaban/i,/clarithromycin|itraconazole|ketoconazole/i,'high','May increase anticoagulant exposure'],[/rivaroxaban|apixaban/i,/ibuprofen|diclofenac|naproxen|aspirin/i,'high','Bleeding risk'],[/clopidogrel/i,/omeprazole|esomeprazole/i,'moderate','May reduce clopidogrel activation'],[/telmisartan|losartan|olmesartan|ramipril/i,/spironolactone/i,'moderate','May increase potassium'],[/methotrexate/i,/trimethoprim|ibuprofen|diclofenac|naproxen/i,'high','Potential methotrexate toxicity'],[/linezolid|tramadol/i,/sertraline|escitalopram|fluoxetine|duloxetine/i,'high','Serotonin toxicity risk'],[/levothyroxine/i,/calcium|iron|magnesium|sucralfate/i,'moderate','May reduce levothyroxine absorption']];
function inject(){const s=document.createElement('style');s.textContent='.sm-fab{position:fixed;right:18px;bottom:18px;z-index:40;border:0;border-radius:999px;padding:14px 17px;background:#0b6b5e;color:#fff;font-weight:900;box-shadow:0 10px 28px #0b6b5e44}.sm-banner{background:#e8f6f2;border:1px solid #cbe7df;padding:12px 14px;border-radius:14px;margin:10px 0}.sm-alert{background:#fff2db;border:1px solid #efd6a6;padding:12px;border-radius:12px;margin:10px 0}.sm-danger{background:#fae8e5;border:1px solid #edc0ba;padding:12px;border-radius:12px;margin:10px 0}.sm-actions{display:flex;gap:8px;flex-wrap:wrap}.sm-preview{max-width:100%;max-height:260px;border-radius:14px;margin-top:10px}.sm-confidence{height:7px;background:#e5eeeb;border-radius:8px;overflow:hidden}.sm-confidence b{display:block;height:100%;background:#0b6b5e}.sm-chip{display:inline-block;padding:5px 8px;border-radius:999px;background:#eef6f3;color:#0b6b5e;font-size:11px;font-weight:800;margin:3px}.sm-step{display:flex;gap:10px;align-items:center;margin:8px 0}.sm-step strong{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#0b6b5e;color:#fff}.sm-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:600px){.sm-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
async function notify(title,body){if(!('Notification'in window)){toast('Notifications are not supported.');return false}if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission==='granted'){new Notification(title,{body,tag:'smartmed-dose'});return true}toast('Allow notifications for Smart Med.');return false}
function reminderLoop(){const d=get();if(!d?.meds)return;const n=new Date(),hm=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0'),day=n.toISOString().slice(0,10);d.meds.filter(m=>m.active!==false&&m.status==='confirmed').forEach(m=>(m.times||[]).forEach(time=>{const k='smrem:'+day+':'+m.id+':'+time;if(time===hm&&!localStorage.getItem(k)){localStorage.setItem(k,'1');notify('Time for '+m.name,`${m.dose||''} • ${time}. Open Smart Med to record Taken or Skip.`)}}))}
function markDose(id,taken){const d=get();if(!d)return;const m=d.meds.find(x=>x.id===id);if(!m)return;m.adherence=Array.isArray(m.adherence)?m.adherence:[];m.adherence.push(taken?1:0);m.adherence=m.adherence.slice(-30);if(taken&&typeof m.refill==='number'&&m.refill>0)m.refill--;d.events=d.events||[];d.events.unshift({t:new Date().toLocaleString(),x:`${m.name} dose marked ${taken?'taken':'skipped'}`});d.events=d.events.slice(0,30);set(d);toast(taken?'Dose recorded ✓':'Dose skipped');window.render?.()}
function modal(inner){const d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="sheet">${inner}</div>`;document.body.appendChild(d);return d}
function screenTextDemo(){return `Patient: Ravindra Deshmukh\nRx: Warfarin 5 mg once daily at 08:00\nLosartan 50 mg once daily at 20:00\nDuration: 30 days`}
function extract(text){const found=[];for(const name of DRUGS){const re=new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');if(re.test(text)){let dose='';const m=text.match(new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s+(\\d+(?:\\.\\d+)?\\s*(?:mg|mcg|g|ml))','i'));dose=m?m[1]:'';let time=(/warfarin/i.test(name)?'08:00':/losartan|amlodipine|metformin/i.test(name)?'20:00':'09:00');const tm=text.match(new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'[^\\n]*?(\\d{1,2}:\\d{2})','i'));if(tm)time=tm[1];found.push({name,dose:dose||'Strength not detected',time,confidence:dose?94:76})}}return found}
function interactionFor(name){const d=get()||{meds:[]};let hits=[];for(const m of d.meds||[]){for(const r of RULES){if((r[0].test(name)&&r[1].test(m.name))||(r[1].test(name)&&r[0].test(m.name)))hits.push({with:m.name,level:r[2],reason:r[3]})}}return hits}
function scanner(){const x=modal(`<h2>AI Prescription Scanner</h2><div class="sm-step"><strong>1</strong><div><b>Capture</b><div class="small muted">Take a clear prescription photo or upload one.</div></div></div><input id="rxFile" type="file" accept="image/*" capture="environment"><div id="rxPreview"></div><div class="sm-step"><strong>2</strong><div><b>Extract & review</b><div class="small muted">Assistive extraction only. Verify against the original prescription.</div></div></div><textarea id="rxText" rows="5" style="width:100%;padding:11px;border:1.5px solid #dce8e4;border-radius:10px" placeholder="For demo: enter prescription text, e.g. Warfarin 5 mg once daily at 08:00"></textarea><div class="sm-actions"><button class="btn outline" id="demoRx">Load demo prescription</button><button class="btn primary" id="extractRx">Extract medicines</button></div><div id="rxResults"></div><div class="sm-step"><strong>3</strong><div><b>Safety gate</b><div class="small muted">Potential interactions are flagged for pharmacist review.</div></div></div><div id="rxSafety"></div><div class="sm-actions"><button class="btn primary" id="sendRx">Send verified selection to pharmacist</button><button class="btn outline" id="rxClose">Close</button></div>`);
let image='';let items=[];x.querySelector('#rxClose').onclick=()=>x.remove();x.querySelector('#demoRx').onclick=()=>x.querySelector('#rxText').value=screenTextDemo();x.querySelector('#rxFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{image=r.result;x.querySelector('#rxPreview').innerHTML=`<img class="sm-preview" src="${image}" alt="Prescription preview"><div class="sm-banner"><b>Image captured.</b> For this prototype, extraction is demonstrated from user-entered text; production OCR requires a validated OCR/AI backend.</div>`};r.readAsDataURL(f)};
x.querySelector('#extractRx').onclick=()=>{items=extract(x.querySelector('#rxText').value);renderExtract(x,items)};
x.querySelector('#sendRx').onclick=()=>{const d=get()||{meds:[],events:[]};d.meds=d.meds||[];d.events=d.events||[];let added=0;items.filter(i=>i.selected!==false).forEach(i=>{const id='rx'+Date.now()+Math.random().toString(16).slice(2);d.meds.push({id,name:i.name,dose:i.dose,route:'Oral',times:[i.time],status:'pending',active:true,adherence:[],refill:30});added++});d.events.unshift({t:new Date().toLocaleString(),x:`AI prescription extraction submitted: ${added} medicine(s) awaiting pharmacist verification`});set(d);toast('Prescription sent to pharmacist queue');x.remove();window.render?.()};
}
function renderExtract(x,items){const r=x.querySelector('#rxResults'),s=x.querySelector('#rxSafety');if(!items.length){r.innerHTML='<div class="sm-alert"><b>No medicines confidently detected.</b><br>Try the demo prescription or enter medicine names manually.</div>';s.innerHTML='';return}r.innerHTML=`<div class="card"><h3>Extracted prescription</h3>${items.map((i,n)=>`<div class="row"><div><input type="checkbox" data-rxcheck="${n}" checked style="width:auto;margin-right:6px"><b>${esc(i.name)}</b><span class="sm-chip">${i.confidence}% confidence</span><div class="small muted">${esc(i.dose)} · once daily · ${i.time}</div><div class="sm-confidence"><b style="width:${i.confidence}%"></b></div></div><select data-rxtime="${n}" style="max-width:110px"><option ${i.time==='08:00'?'selected':''}>08:00</option><option ${i.time==='09:00'?'selected':''}>09:00</option><option ${i.time==='13:00'?'selected':''}>13:00</option><option ${i.time==='20:00'?'selected':''}>20:00</option></select></div>`).join('')}</div>`;r.querySelectorAll('[data-rxcheck]').forEach(c=>c.onchange=()=>items[c.dataset.rxcheck].selected=c.checked);r.querySelectorAll('[data-rxtime]').forEach(c=>c.onchange=()=>items[c.dataset.rxtime].time=c.value);let hits=[];items.forEach(i=>hits.push(...interactionFor(i.name)));hits=hits.filter((v,i,a)=>a.findIndex(q=>q.with===v.with&&q.reason===v.reason)===i);s.innerHTML=hits.length?`<div class="sm-alert"><b>Pharmacist safety review required</b>${hits.map(h=>`<div class="row"><span><b>${esc(h.with)}</b><br><span class="small">${esc(h.reason)}</span></span><span class="pill ${h.level==='high'?'bad':'warn'}">${h.level}</span></div>`).join('')}</div>`:'<div class="sm-banner"><b>No embedded-rule match detected.</b><br>This is not a complete interaction checker; pharmacist review remains required.</div>'}
function toolsModal(){const d=get()||{};const x=modal(`<h2>Smart Med+</h2><p class="muted">Competition demonstration control center</p><div class="card"><h3>AI Prescription Scanner</h3><p class="small muted">Capture → extract → confidence → safety gate → pharmacist verification → schedule.</p><button class="btn primary" id="openScanner">Open AI Scanner</button></div><div class="card"><h3>Medication reminders</h3><button class="btn primary" id="smNotify">Enable notifications</button><p class="small muted">Browser reminders require the app to remain active.</p></div><div class="card"><h3>Caregiver escalation</h3><button class="btn outline" id="smMiss">Simulate missed dose</button> <button class="btn outline" id="smEmergency">Emergency workflow</button><div id="smEsc"></div></div><div class="card"><h3>Care team</h3><div class="row"><b>Patient</b><span>${esc(d.name||'Demo patient')}</span></div><div class="row"><b>Caregiver</b><span>${esc(d.caregiver||'Caregiver')}</span></div><div class="row"><b>Doctor</b><span>${esc(d.doctor||'Doctor')}</span></div><div class="row"><b>Pharmacy</b><span>${esc(d.pharmacy||'Pharmacy')}</span></div></div><button class="btn outline" id="smClose">Close</button>`);x.querySelector('#smClose').onclick=()=>x.remove();x.querySelector('#openScanner').onclick=()=>{x.remove();scanner()};x.querySelector('#smNotify').onclick=()=>notify('Smart Med notifications enabled','Medication reminder alerts are enabled while the app is active.');x.querySelector('#smMiss').onclick=()=>{const a=get();a.events=a.events||[];a.events.unshift({t:new Date().toLocaleString(),x:'Missed-dose escalation triggered: caregiver notification queued'});set(a);x.querySelector('#smEsc').innerHTML='<div class="sm-alert"><b>Escalation queued</b><br>Caregiver alert → pharmacist review → patient follow-up.</div>';toast('Caregiver escalation simulated')};x.querySelector('#smEmergency').onclick=()=>{const a=get();a.events=a.events||[];a.events.unshift({t:new Date().toLocaleString(),x:'Emergency workflow initiated'});set(a);x.querySelector('#smEsc').innerHTML='<div class="sm-danger"><b>Emergency workflow</b><br>This demo records the workflow only; it does not place emergency calls.</div>'}}
function boot(){inject();const l=document.createElement('link');l.rel='manifest';l.href='./manifest.json';document.head.appendChild(l);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const b=document.createElement('button');b.className='sm-fab';b.textContent='AI Scanner';b.onclick=scanner;document.body.appendChild(b);document.addEventListener('click',e=>{const t=e.target.closest('[data-take]');if(t){e.preventDefault();markDose(t.dataset.take,true)}const s=e.target.closest('[data-skip]');if(s){e.preventDefault();markDose(s.dataset.skip,false)}});setInterval(reminderLoop,15000);reminderLoop();window.addEventListener('online',()=>toast('Smart Med is online'));window.addEventListener('offline',()=>toast('Offline mode enabled'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();