(()=>{
'use strict';
const KEY='smartmed-live';
const demo={id:'SM-10001',name:'Rajesh Kumar',dob:'14 March 1982',age:44,sex:'Male',phone:'+91 98765 43210',blood:'B+',allergies:['Penicillin'],conditions:['Hypertension','Type 2 Diabetes'],doctor:'Dr. Anil Sharma',doctorPhone:'+91 98220 11223',emergency:'Sunita Kumar',emergencyPhone:'+91 98765 99887',meds:[{name:'Metformin',dose:'500 mg',route:'Oral',frequency:'Twice daily',times:'08:00, 20:00',status:'Active'},{name:'Telmisartan',dose:'40 mg',route:'Oral',frequency:'Once daily',times:'08:00',status:'Active'},{name:'Atorvastatin',dose:'20 mg',route:'Oral',frequency:'Once daily',times:'21:00',status:'Active'}]};
function get(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&s.name)return {...demo,name:s.name,allergies:s.allergies?.length?s.allergies:demo.allergies,conditions:s.conditions?.length?s.conditions:demo.conditions};}catch(e){}return demo}
function add(){if(document.getElementById('patientRecordBtn'))return;const b=document.createElement('button');b.id='patientRecordBtn';b.textContent='👤 Patient Record';Object.assign(b.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:80,border:0,borderRadius:'999px',padding:'13px 17px',background:'#087f6b',color:'#fff',fontWeight:'900',boxShadow:'0 8px 24px #123c3230'});b.onclick=open;b.title='Open patient record';document.body.appendChild(b)}
function open(){const p=get();const meds=p.meds.map(m=>`<div style="display:flex;justify-content:space-between;gap:10px;padding:12px 0;border-bottom:1px solid #e6eeeb"><div><b>${esc(m.name)}</b><div style="color:#667b76;font-size:12px">${esc(m.dose)} · ${esc(m.route)} · ${esc(m.frequency)}</div></div><span style="background:#e7f6ed;color:#16834b;padding:5px 8px;border-radius:99px;font-size:11px;font-weight:800">${esc(m.status)}</span></div>`).join('');const x=document.createElement('div');x.style.cssText='position:fixed;inset:0;background:#092b2677;z-index:100;display:grid;place-items:end';x.innerHTML=`<div style="width:min(720px,100%);max-height:94vh;overflow:auto;background:white;border-radius:24px 24px 0 0;padding:22px;font:14px system-ui;color:#15342f"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:11px;font-weight:900;letter-spacing:1.4px;color:#087f6b">SMART MED · PATIENT RECORD</div><h2 style="margin:5px 0">${esc(p.name)}</h2><div style="color:#667b76">Patient ID: ${esc(p.id)} · ${esc(p.age)} years · ${esc(p.sex)}</div></div><button id="prClose" style="border:0;border-radius:50%;width:36px;height:36px;font-size:22px">×</button></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0"><div style="background:#f3f7f5;padding:12px;border-radius:12px"><small>Blood group</small><b style="display:block">${esc(p.blood)}</b></div><div style="background:#f3f7f5;padding:12px;border-radius:12px"><small>Allergies</small><b style="display:block">${esc(p.allergies.join(', '))}</b></div><div style="background:#f3f7f5;padding:12px;border-radius:12px"><small>Conditions</small><b style="display:block">${esc(p.conditions.join(', '))}</b></div></div><div style="background:#fff2f0;border:1px solid #efc2bd;border-radius:12px;padding:12px;margin-bottom:15px"><b>⚠ Allergy alert</b><div>Documented allergy: ${esc(p.allergies.join(', '))}</div></div><h3>Active Medications</h3>${meds}<h3 style="margin-top:18px">Care Information</h3><div style="background:#f3f7f5;border-radius:12px;padding:14px;line-height:1.8"><b>Doctor:</b> ${esc(p.doctor)}<br><b>Doctor phone:</b> ${esc(p.doctorPhone)}<br><b>Emergency contact:</b> ${esc(p.emergency)}<br><b>Emergency phone:</b> ${esc(p.emergencyPhone)}<br><b>Patient phone:</b> ${esc(p.phone)}</div><p style="font-size:11px;color:#667b76;margin-top:15px">Demo patient record for application testing. Replace with authenticated patient data before clinical deployment.</p></div>`;document.body.appendChild(x);x.querySelector('#prClose').onclick=()=>x.remove()}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();