-- Smart Med production database foundation (Supabase/PostgreSQL)
-- Run only after creating your own Supabase project.
create extension if not exists pgcrypto;
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', dob date, phone text, blood_group text, emergency_name text, emergency_phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists medications (id uuid primary key default gen_random_uuid(), patient_id uuid not null references auth.users(id) on delete cascade, name text not null, normalized_name text, strength text, dose text, route text, instructions text, times jsonb not null default '[]'::jsonb, quantity numeric, remaining_quantity numeric, active boolean not null default true, verification_status text not null default 'pending' check (verification_status in ('pending','verified','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists dose_events (id uuid primary key default gen_random_uuid(), patient_id uuid not null references auth.users(id) on delete cascade, medication_id uuid not null references medications(id) on delete cascade, scheduled_at timestamptz not null, recorded_at timestamptz, status text not null check (status in ('scheduled','taken','skipped','missed')), created_at timestamptz not null default now());
create table if not exists allergies (id uuid primary key default gen_random_uuid(), patient_id uuid not null references auth.users(id) on delete cascade, allergen text not null, reaction text, severity text, created_at timestamptz not null default now());
create table if not exists conditions (id uuid primary key default gen_random_uuid(), patient_id uuid not null references auth.users(id) on delete cascade, condition_name text not null, created_at timestamptz not null default now());
create table if not exists care_team (id uuid primary key default gen_random_uuid(), patient_id uuid not null references auth.users(id) on delete cascade, name text not null, role text not null, phone text, email text, created_at timestamptz not null default now());
create table if not exists prescriptions (id uuid primary key default gen_random_uuid(), patient_id uuid not null references auth.users(id) on delete cascade, image_path text, extracted_data jsonb, status text not null default 'pending' check (status in ('pending','reviewed','approved','rejected')), reviewer_id uuid references auth.users(id), created_at timestamptz not null default now(), reviewed_at timestamptz);
create table if not exists audit_events (id uuid primary key default gen_random_uuid(), patient_id uuid references auth.users(id) on delete set null, actor_id uuid references auth.users(id) on delete set null, action text not null, entity_type text, entity_id uuid, metadata jsonb, created_at timestamptz not null default now());
alter table profiles enable row level security; alter table medications enable row level security; alter table dose_events enable row level security; alter table allergies enable row level security; alter table conditions enable row level security; alter table care_team enable row level security; alter table prescriptions enable row level security; alter table audit_events enable row level security;
create policy "own profile" on profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy "own medications" on medications for all using (patient_id=auth.uid()) with check (patient_id=auth.uid());
create policy "own doses" on dose_events for all using (patient_id=auth.uid()) with check (patient_id=auth.uid());
create policy "own allergies" on allergies for all using (patient_id=auth.uid()) with check (patient_id=auth.uid());
create policy "own conditions" on conditions for all using (patient_id=auth.uid()) with check (patient_id=auth.uid());
create policy "own care team" on care_team for all using (patient_id=auth.uid()) with check (patient_id=auth.uid());
create policy "own prescriptions" on prescriptions for all using (patient_id=auth.uid()) with check (patient_id=auth.uid());
create policy "own audit" on audit_events for select using (patient_id=auth.uid());
